name: test

on:
  pull_request:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly

      - name: luajit
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - name: luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: run test
        shell: bash
        run: |
          luarocks install luacheck
          luarocks install vusted
          make test

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Setup build dependencies
      run: |
        brew install luarocks
        brew install neovim
    - name: Run test with building Nvim
      run: |
        luarocks install vusted
        make test
