name: test

on:
  pull_request:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Setup build dependencies
      run: |
        sudo apt update &&
        sudo apt install -y ninja-build \
          gettext \
          cmake \
          g++ \
          unzip
    - name: Run test with building Nvim
      run: make test
  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Setup build dependencies
      run: brew install ninja
    - name: Run test with building Nvim
      run: make test

