name: test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-openresty"
      - uses: leafo/gh-actions-luarocks@v4

      - name: Install vusted
        run: luarocks install vusted

      - name: Run test
        run: vusted ./test
