---@meta

---@class _.lspconfig.settings.stylelint_language_server.Stylelint.CodeAction.DisableRuleComment
---Configure whether disable comments are added on the same line or a new line.
---
---```lua
---default = "separateLine"
---```
---@field location? "separateLine" | "sameLine"

---@class _.lspconfig.settings.stylelint_language_server.Stylelint.CodeAction
---Options for the disable lint rule action in the quick fix menu.
---
---```lua
---default = {
---  location = "separateLine"
---}
---```
---@field disableRuleComment? _.lspconfig.settings.stylelint_language_server.Stylelint.CodeAction.DisableRuleComment

---@class _.lspconfig.settings.stylelint_language_server.Stylelint.Rules.Customization
---Rule name pattern to match. `*` is treated as a wildcard. Prefix with `!` to match all rules that do not match the pattern.
---@field rule string
---Severity override. `downgrade` converts errors to warnings and warnings to info messages, `upgrade` converts warnings to errors, and `default` preserves Stylelint's original severity.
---@field severity "downgrade" | "upgrade" | "error" | "warn" | "info" | "off" | "default"

---@class _.lspconfig.settings.stylelint_language_server.Stylelint.Rules
---Override severity levels for specific rules.
---
---```lua
---default = {}
---```
---@field customizations? _.lspconfig.settings.stylelint_language_server.Stylelint.Rules.Customization[]

---@class _.lspconfig.settings.stylelint_language_server.Stylelint.LintFiles
---The glob pattern used by the `Lint All Files` and `Lint Workspace Folder` commands to discover files.
---
---```lua
---default = "**/*.css"
---```
---@field glob? string

---@class _.lspconfig.settings.stylelint_language_server.Stylelint
---Controls whether this extension is enabled or not.
---
---```lua
---default = true
---```
---@field enable? boolean
---Controls when the linter runs.
---  `onType`: Runs on each change as you type.
---  `onSave`: Only runs after you save a document.
---
---```lua
---default = "onType"
---```
---@field run? "onSave" | "onType"
---Controls the log level used by the Stylelint extension and language server. Restart the extension host or the window after changing the setting, since it's picked up at initialization.
---
---```lua
---default = "info"
---```
---@field logLevel? "error" | "warn" | "info" | "debug"
---The location of the node binary to run Stylelint under.
---
---```lua
---default = nil
---```
---@field runtime? string
---Additional exec argv arguments passed to the Node.js runtime.
---
---```lua
---default = nil
---```
---@field execArgv? string[]
---@field codeAction? _.lspconfig.settings.stylelint_language_server.Stylelint.CodeAction
---A Stylelint configuration object.
---
---```lua
---default = nil
---```
---@field config? table
---Path to a JSON, YAML, or JS file that contains your configuration object. Use this option if you don't want Stylelint to search for a configuration file.
---
---```lua
---default = ""
---```
---@field configFile? string
---A path to the directory that relative paths defining `extends` and `plugins` are relative to.
---
---```lua
---default = ""
---```
---@field configBasedir? string
---An absolute path to a custom PostCSS-compatible syntax module.
---
---```lua
---default = ""
---```
---@field customSyntax? string
---Path to a file containing patterns describing files to ignore. Use to override automatic `.stylelintignore` detection.
---
---```lua
---default = ""
---```
---@field ignorePath? string
---Report `stylelint-disable` comments without a description.
---
---```lua
---default = false
---```
---@field reportDescriptionlessDisables? boolean
---Ignore `stylelint-disable` comments, for example `/* stylelint-disable block-no-empty */`.
---
---```lua
---default = false
---```
---@field ignoreDisables? boolean
---Report errors for `stylelint-disable` comments that are not blocking a lint warning.
---
---```lua
---default = false
---```
---@field reportNeedlessDisables? boolean
---Report errors for `stylelint-disable` comments that are used for rules that do not exist within the configuration object.
---
---```lua
---default = false
---```
---@field reportInvalidScopeDisables? boolean
---Supply a custom path to the Stylelint module.
---
---```lua
---default = ""
---```
---@field stylelintPath? string
---The package manager you use to install node modules.
---
---```lua
---default = "npm"
---```
---@field packageManager? "npm" | "yarn" | "pnpm"
---An array of language ids which should be validated by Stylelint.
---
---```lua
---default = { "css", "postcss" }
---```
---@field validate? string[]
---An array of language ids which snippets are provided by Stylelint.
---
---```lua
---default = { "css", "postcss" }
---```
---@field snippet? string[]
---@field rules? _.lspconfig.settings.stylelint_language_server.Stylelint.Rules
---@field lintFiles? _.lspconfig.settings.stylelint_language_server.Stylelint.LintFiles

---@class lspconfig.settings.stylelint_language_server
---@field stylelint? _.lspconfig.settings.stylelint_language_server.Stylelint
